### ISSUE TITLE
"neural recording sys = ecube" is broken

### ISSUE THREAD

**Issue by leoscholl** [aolabNeuro/brain-python-interface#67]
##### Error trying to access task entry data: id=1715, dbname=default
Traceback (most recent call last):
  File "/home/pagaiisland/code/bmi3d/db/tracker/ajax.py", line 159, in exp_info
    entry_data = entry.to_json()
  File "/home/pagaiisland/code/bmi3d/db/tracker/models.py", line 871, in to_json
    from riglib.ecube import ecubefile
ImportError: cannot import name 'ecubefile' from 'riglib.ecube' (/home/pagaiisland/code/bmi3d/riglib/ecube/__init__.py)
#####
Internal Server Error: /exp_log/ajax/exp_info/1715/
Traceback (most recent call last):
  File "/home/pagaiisland/code/bmi3d/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/pagaiisland/code/bmi3d/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 186, in _get_response
    self.check_response(response, callback)
  File "/home/pagaiisland/code/bmi3d/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 309, in check_response
    "instead." % name
ValueError: The view db.tracker.ajax.exp_info didn't return an HttpResponse object. It returned None instead.

**Comment by leoscholl** [comment]
fixing this in the branch ecube-decoder-train
