### ISSUE TITLE
reward system manual_reward button not responding sometimes

### ISSUE THREAD

**Issue by leoscholl** [aolabNeuro/brain-python-interface#97]
the error was something about not being able reinstate the Basic object because it's a singleton. i accidentally closed the terminal window when i was trying to copy it. unfortunately the problem isn't getting saved into runserver.log or reward.log

**Comment by leoscholl** [comment]
here's the error, seems to happen pretty often:

Traceback (most recent call last):
  File "/home/pagaiisland/code/bmi3d/riglib/reward.py", line 62, in open
    reward = Basic.get_instance()
  File "/home/pagaiisland/code/bmi3d/riglib/singleton.py", line 9, in get_instance
    cls()
  File "/home/pagaiisland/code/bmi3d/riglib/reward.py", line 25, in __init__
    super().__init__()
  File "/home/pagaiisland/code/bmi3d/riglib/singleton.py", line 17, in __init__
    raise Exception("can't reinstantiate %s because it is a singleton!" % self.__class__.__name__)
Exception: can't reinstantiate Basic because it is a singleton!
